destination: _site
exclude:
  - buildSite.bat
  - deploy_key.enc
  - Gemfile
  - Gemfile.lock
  - cibuild
  - deploy.sh

permalink: /404.html

# Site settings
title: Workshop FRC LabVIEW Tutorials
description: > # this means to ignore newlines until the next yaml key.
  As an offshoot of FRCLabVIEWTutorials.com, this site is a compilation of past and current LabVIEW workshop resources.

# Build settings
markdown: kramdown
